# Generated by Django 5.2.10 on 2026-01-28 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_form_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название объекта')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бизнес-объект',
                'verbose_name_plural': 'Бизнес-объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_form_test.role', verbose_name='Роль пользователя'),
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_read', models.BooleanField(default=False, verbose_name='Может просматривать')),
                ('can_create', models.BooleanField(default=False, verbose_name='Может создавать')),
                ('can_update', models.BooleanField(default=False, verbose_name='Может обновлять')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Может удалять')),
                ('can_read_all', models.BooleanField(default=False, verbose_name='Может просматривать все')),
                ('can_update_all', models.BooleanField(default=False, verbose_name='Может обновлять все')),
                ('can_delete_all', models.BooleanField(default=False, verbose_name='Может удалять все')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_form_test.businesselement', verbose_name='Бизнес-объект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_form_test.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'ordering': ['role', 'element'],
                'unique_together': {('role', 'element')},
            },
        ),
    ]
